### ISSUE TITLE
Calculation of evaluation metrics on gate.ac.uk seems to be inaccurate.?

### ISSUE THREAD

**Issue by andreofner** [andreofner/NER_review#12]
In detail:
1) correct hits not defined = coextensive hits?
2) definition of SPURIOUS wrong? 
	Should be: …included in the key annotation.
	Instead of: …included in the response annotation.
3) Recall and Precision Formula wrong?

On gate.ac.uk:
P = PRECISION 	= (CORRECT +0.5 * PARTIAL) 	/ (CORRECT+SPURIOUS+**PARTIAL**) 
R = RECALL 		= (CORRECT +0.5 * PARTIAL) 	/ (CORRECT+MISSING+**PARTIAL**) 

In other sources:
P = PRECISION 	= (CORRECT +0.5 * PARTIAL) 	/ (CORRECT+SPURIOUS+**0.5 * PARTIAL**) 
R = RECALL 		= (CORRECT +0.5 * PARTIAL) 	/ (CORRECT+MISSING+**0.5 * PARTIAL**) 

For example in this paper they quote the metrics used by the gate tool differently: https://gate.ac.uk/sale/ranlp2001/maynard-etal.pdf

But then, they state (in https://gate.ac.uk/sale/ranlp2001/maynard-etal.pdf): 
" The weighting for the F-measure is 0.5, i.e. equal preference is given to precision and recall" 
Which is also not correct I think..

**Comment by jmcejuela** [comment]
1) After quote later, I would say:
  * correct: same entity type & same offsets
  * partial: same entity type & overlapping offsets

> Note that we consider annotations to be partially correct if the entity type is correct and the spans are overlapping but not identical. Partially correct responses are normally allocated a half weight.

2) Spurious: False Positive (ie, in prediction but not in gold/test annotations)
3) Good question. I would say the version on the web is correct (this is what I used so far for other projects), that is:

```
P = PRECISION = (CORRECT +0.5 * PARTIAL) / (CORRECT+SPURIOUS+PARTIAL) 
R = RECALL = (CORRECT +0.5 * PARTIAL) / (CORRECT+MISSING+PARTIAL)
```

However, it would be great if you could contrast this info with yet another source. I think the other definition would create a bias for methods tending to overlap everything.

4) F-measure with weight 1 (F1) gives equal value to precision & recall. When 1, the F-Measure is equivalent to the harmonic mean

**Comment by jmcejuela** [comment]
lets review it together next week

**Comment by jmcejuela** [comment]
Since the paper had an obvious mistake in the F1 calculation, we go for the rather official information of the gate webpage
